=== brzegator27/JiTW-PHP-project/test_2015/problem_6/wloskie_makarony.dtd
<!ELEMENT wloskie_makarony (gatunek_makaronu)*>
<!ELEMENT wloski_makaron (gatunek_makaronu, skladnik+, przyprawa*)>
<!ELEMENT gatunek_makaronu (#PCDATA)>
<!ELEMENT skladnik (#PCDATA)>
<!ELEMENT przyprawa (#PCDATA)>

<!ATTLIST wloski_makaron indentyfikator ID #REQUIRED>
<!ATTLIST skladnik ilosc CDATA #REQUIRED>
<!ATTLIST skladnik jednostka CDATA #REQUIRED>

=== brzegator27/JiTW-PHP-project/test_2015/problem_6/przepisy_wloskie_makarony.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wloskie_makarony SYSTEM "wloskie_makarony.dtd">

<wloskie_makarony>
    <wloski_makaron identyfikator="1">
        <gatunek_makaronu>
            JakiÅ› gatunek 1
        </gatunek_makaronu>
        <skladnik>
            skl. 1
        </skladnik>
        <skladnik>
            skl. 1
        </skladnik>
        <przyprawa>
            prz. 1
        </przyprawa>
    </wloski_makaron>
    <wloski_makaron identyfikator="2">
        <gatunek_makaronu>
            JakiÅ› gatunek 1
        </gatunek_makaronu>
        <skladnik>
            skl. 1
        </skladnik>
    </wloski_makaron>
</wloskie_makarony>
